OUT = mocc

CC = clang
RM = rm -rf

FLAGS = -Wall -Wextra -ggdb -nostdlib -static -Werror
INCL = -Imusl-1.2.6/include -Imusl-1.2.6/obj/include
LIBDIR = musl-1.2.6/lib
LIBS = $(LIBDIR)/crt1.o $(LIBDIR)/crti.o $(LIBDIR)/crtn.o -L$(LIBDIR) -Lmusl-1.2.6/arch/x86_64 -lc

SRC_DIR = src
SRC = $(filter-out $(GEN_SRC),$(shell find $(SRC_DIR) -name "*.c"))
OBJ_DIR = obj
OBJ = $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(SRC) $(GEN_SRC))
HEADERS_DIR = src
HEADERS = $(filter-out $(GEN_HEAD),$(wildcard $(INC_DIR)/*.h))) $(GEN_HEAD)

# Autogenerated
GEN_SRC = $(SRC_DIR)/lexer.c $(SRC_DIR)/parser.c
GEN_HEAD = $(HEADERS_DIR)/parser.h

MACHINE = $(shell clang -dumpmachine)

all: $(OUT)

.PHONY: $(OUT)
$(OUT): $(OBJ)
	$(CC) $(FLAGS) $^ $(LIBS) $(LDFLAGS) -o $@

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c
	@ mkdir -p $(OBJ_DIR)
	$(CC) $(FLAGS) $(INCL) -c $^ -o $@

# Additional dependencies
$(OBJ_DIR)/%.o: $(HEADERS) Makefile

$(SRC_DIR)/lexer.c: src/lexer.re
	re2c $^ -o $@
	@ touch $@

# src/ must equal SRC_DIR and HEADERS_DIR -- todo: fix this
$(SRC_DIR)/parser.c $(HEADERS_DIR)/parser.h: src/parser.y
	lemon $^ -q
	@ touch $@

clean:
	$(RM) $(OBJ_DIR)
